### ISSUE TITLE
TODO: rewrite build config, build from git instead of sdist, make nightly builds available, and more improvements

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-appimage#2]
The AppImage build config and build scripts should be rewritten so that they match the ones of Streamlink's Windows builds (installers and portable archives). Streamlink's code should be retrieved from git instead of stable sdist releases from PyPI, and nightly builds should be published as build artifacts. Building dependencies from source instead of downloading pre-built wheels should also be explored, so we're not limited by any build- or infrastructure issues of the devs of Streamlink's dependencies (like lxml for example). Optionally, a changelog should be added and the GitHub release should have a message attached (release body).

- [ ] Update build config and scripts
  - [ ] Use the same script arguments as Streamlink's Windows build scripts
  - [ ] Retrieve Streamlink from git
  - [ ] Build dependencies from source
  - [ ] Ensure that everything stays reproducible
- [ ] Publish nightly builds
- [ ] GH releases body
- [ ] Add changelog

**Comment by bastimeyer** [comment]
Adding this as an optional comment, as it doesn't actually belong into this thread but on the streamlink/appimage-buildenv repo instead:

- [ ] Update squashfs-tools sources and appimagetool
- [ ] Explore building appimagetool from source (only had a short look at this a few months ago, and it seemed rather unnecessarily and the setup a bit too complex)

**Comment by bastimeyer** [comment]
I've pushed some unfinished changes to the `rewrite` branch, but before this will be merged into `master`, some more stuff needs to be updated:
https://github.com/streamlink/streamlink-appimage/compare/master...rewrite

I've also locally built docker images for building all python dependencies from source, namely `lxml` and `pycryptodome`, so we're not dependent on the pre-built wheels uploaded by the package maintainers to pypi. `lxml` is the issue here once again, because it's still missing some wheels for being able to build cp311 AppImages:
streamlink/streamlink#4903

The docker images therefore need to build `libxml2`, `libxslt` and `libiconv` for lxml, as well as `gmp` for pycryptodome. This unfortunately takes a really long time when emulating aarch64 on x86_64. It wouldn't be too much of an issue as it's a one-time thing only, but building the python wheels in the containers here after pulling the images with the built dependencies takes even more time, about 40mins on my Ryzen 3950X, which means it'll be at least twice as long on the GitHub CI-runners, which is bad when publishing new releases or building nightlies and trying to check the results. This means another pre-build step would be needed where the wheels get built, and those pre-built custom wheels would need to be added to the package data in `config.json`. Not a great solution. It also breaks the reproducibility of the AppImages, because when building the wheels locally, the result is non-deterministic. So I probably won't continue with building all deps from source.
